### ISSUE TITLE
Component does not start on version 1.6.8

### ISSUE THREAD

**Issue by sebcaps** [Cyr-ius/hass-livebox-component#41]
Since update to 1.6.8 got the following error message
`Logger: homeassistant.setup
Source: setup.py:172
First occurred: 8:28:17 (1 occurrences)
Last logged: 8:28:17

Setup failed for livebox: Unable to import component: cannot import name 'STATE_CLASS_MEASUREMENT' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)`

Current HA config 
## System Health

version | core-2021.5.5
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.10.17-v7l+
arch | armv7l
timezone | Europe/Paris

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4911
Installed Version | 1.15.2
Stage | running
Available Repositories | 944
Installed Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | failed to load: timeout

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 1
views | 9
mode | storage

</details>

**Comment by sebcaps** [comment]
Seems good after upgrading to HA
<html>
<body>


core-2021.9.5
--



</body>
</html>

**Comment by sebcaps** [comment]
Closing, the issue.
