### ISSUE TITLE
binary_sensor not all attributes working

### ISSUE THREAD

**Issue by SNoof85** [Cyr-ius/hass-livebox-component#40]
Some binary sensors attributes are broken with 1.6.8

Here is the trace : 
```
Logger: homeassistant.components.binary_sensor
Source: custom_components/livebox/binary_sensor.py:61
Integration: Capteur binaire (documentation, issues)
First occurred: 23:38:10 (2 occurrences)
Last logged: 23:38:11

Error adding entities for domain binary_sensor with platform livebox
Error while setting up livebox platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 698, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/livebox/binary_sensor.py", line 61, in device_state_attributes
    uptime = datetime.today() - timedelta(
TypeError: unsupported type for timedelta seconds component: NoneType
```

**Comment by oncleben31** [comment]
Same thing for me.

**Comment by oncleben31** [comment]
No problem with 1.6.6

**Comment by tomtomdu85** [comment]
Hi everybody.

After update from 1.6.6  to 1.6.8, I've got an error :

Setup failed for livebox: Unable to import component: cannot import name 'SensorEntityDescription' from 'homeassistant.components.sensor' (/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/sensor/__init__.py)

The integration can't be loaded.

I'm go back to 1.6.6

Thanks
